import Head from 'next/head'
import Image from 'next/image'
import Sidebar from '../components/Sidebar'
import Feed from '../components/Feed';

import 'tailwindcss/tailwind.css';
import Widgets from '../components/Widgets';
import CommentModal from '../components/CommentModal';
import { getAuth } from "firebase/auth";
import { listAll } from "firebase/storage";

export default function Home() {
  return (
    <div >
      <Head>
        <title>Blip</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen min-w-screen bg-black">
        
        <Feed/>
        <Sidebar/>
         
<CommentModal />

      </main>
      

     
    </div>
  )
}
export async function getServerSideProps() {
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
  ).then((res) => res.json());
const randomUsersResults=await fetch("https://randomuser.me/api/?results=30&inc=name,login,picture").then((res)=>res.json());

  return {
    props: {
      newsResults,
      randomUsersResults,
    },
  };
}